# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
target 'Test_F' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_F
  pod 'Alamofire', '~> 5.4.4'
  pod 'Moya/RxSwift', '~> 15.0.0'
  pod 'ObjectMapper', '~> 4.2.0'
  pod 'RxSwift', '~> 6.2.0'

end
